[project]
name = "ttestt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "EliasSchlie", email = "EliasSchlie@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ttestt = "ttestt:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
